# Generated by Django 6.0.2 on 2026-03-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties_owner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
    ]
